<a href="https://colab.research.google.com/github/KRiver28/prac/blob/master/pandas0126.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
path = 'movies.xls'
movies =pd.read_excel(path, skiprows=4)
movies.head()

           영화명               영화명(영문)  ...        감독                             제작사
0  장민호 드라마 최종회      Jang Minho Drama  ...       NaN  씨제이 씨지브이(CJ CGV)(주),CGV ICECON
1      서바이벌리스트       The Survivalist  ...       NaN                             NaN
2          코만도          The Commando  ...  아시프 아크바르                             NaN
3      내 친구의 봄                   NaN  ...       NaN                             NaN
4    레스큐 더 파일럿  The Shelburn Network  ...       NaN                             NaN

[5 rows x 9 columns]

In [4]:
movies.count()

영화명        59258
영화명(영문)    47586
제작연도       59258
제작국가       57438
유형         59153
장르         55992
제작상태       59025
감독         43059
제작사         8425
dtype: int64

In [5]:
movies.shape

(59258, 9)

In [7]:
movies.sort_values('제작연도')

                              영화명  ...                             제작사
59257   레슨/달이지고 비가 옵니다/저푸른 초원(단편)  ...                             NaN
41781                   하늘을 나는 교실  ...                             NaN
41782                     하트 오브 미  ...                             NaN
41783                  하트 오브 아메리카  ...                             NaN
41784                          하폰  ...                             NaN
...                           ...  ...                             ...
1064          닥터 스트레인지: 대혼돈의 멀티버스  ...                             NaN
37     오오극장 개관 7주년 특별전 - 대구독립단편신작  ...                             NaN
1592                      그녀가 죽었다  ...                           엔진 필름
377                        백조의 호수  ...                             NaN
0                     장민호 드라마 최종회  ...  씨제이 씨지브이(CJ CGV)(주),CGV ICECON

[59258 rows x 9 columns]

In [10]:
#감독판 영화 추출하기
condition = movies['영화명'].str.contains('감독판')
movies[condition].head()

                   영화명         영화명(영문)  제작연도  ... 제작상태        감독           제작사
799   우리 바꿔서 할래요?(감독판)             NaN  2021  ...   개봉       김감독  (주)더레드엔터테인먼트
2592        마사지의 신 감독판  God of Massage  2021  ...   기타       이시영       (주)룬컴퍼니
4067        바람이 분다 감독판      Wind Blows  2021  ...   기타       선우용       (주)룬컴퍼니
4730      미스터 노바디: 감독판      Mr. Nobody  2009  ...   기타  자코 반 도마엘           NaN
4788     퀴어영화 뷰티풀(감독판)             NaN  2018  ...   기타       백인규        99film

[5 rows x 9 columns]

In [15]:
#감독판 영화의 갯수
condition = movies['영화명'].str.contains('감독판')
movies[condition].count()['영화명']

161

In [17]:
#감독판 영화를 제작 연도로 정렬
movies[condition].sort_values('제작연도')

                    영화명  ...           제작사
35248       라이 위드 미 감독판  ...           NaN
57591           오감도 감독판  ...           NaN
29212           금병매 감독판  ...           NaN
30575         세 얼간이 감독판  ...           NaN
35246        바람의 소리 감독판  ...           NaN
...                 ...  ...           ...
12911       미스터 좀비(감독판)  ...          ㈜리필름
6759       엄마의 직업 2 감독판  ...      (주)나우콘텐츠
4067         바람이 분다 감독판  ...       (주)룬컴퍼니
2592         마사지의 신 감독판  ...       (주)룬컴퍼니
799    우리 바꿔서 할래요?(감독판)  ...  (주)더레드엔터테인먼트

[161 rows x 9 columns]

In [19]:
#2015~2020 제작 영화
condition = (movies['제작연도'] >= 2015) & (movies['제작연도'] <= 2020)
movies[condition]

                       영화명               영화명(영문)  제작연도  ...  제작상태     감독       제작사
3                  내 친구의 봄                   NaN  2016  ...    기타    NaN       NaN
4                레스큐 더 파일럿  The Shelburn Network  2019  ...    기타    NaN       NaN
7        그 남자의 발정 그 여자의 사정                   NaN  2020  ...  개봉예정  제임스 오  (주)뮤직엔닷컴
9             맛집:친구 엄마 무삭제                   NaN  2020  ...  개봉예정  제임스 오  (주)뮤직엔닷컴
13            지당박부원 선생과 톡톡                   NaN  2020  ...    기타    NaN       NaN
...                    ...                   ...   ...  ...   ...    ...       ...
38584  2월 인디애니씨앗터 '너를 찾아서'                   NaN  2015  ...    기타    NaN       NaN
38685     부산지역 대학 작품 상영 02                   NaN  2015  ...    기타    NaN       NaN
38686     부산지역 대학 작품 상영 03                   NaN  2015  ...    기타    NaN       NaN
38687     부산지역 대학 작품 상영 01                   NaN  2015  ...    기타    NaN       NaN
38906                제 2계획                   NaN  2015  ...  촬영준비    박희권  (주)고앤고필름

[27995 rows x 9 columns]

In [ ]:
#apply함수